### PR TITLE
fix: forceAlign should not use outdated onAlign callback

### LINKED ISSUE #85: forceAlign uses outdated onAlign callback
Look here :) 

https://github.com/react-component/align/blob/93641c5afcbb85362db9df2f32c49b56eac3f597/src/Align.tsx#L91

It seems that the `onAlign` prop is cached as `forceAlignPropsRef.current.onAlign`, such that it can be used inside the callback passed into `useBuffer`, using the latest passed in props value.

However, that whole code does not use the `forceAlignPropsRef.current.onAlign` value, but the closured `onAlign` value instead. I think this is wrong, and I believe it is causing ant-design/ant-design#27018.

It is all already prepared. I think we just have to use onAlign the same way we use `disabled` & `target` in [L67](https://github.com/react-component/align/blob/93641c5afcbb85362db9df2f32c49b56eac3f597/src/Align.tsx#L67), destructuring it to `latestOnAlign`.

### PR DESCRIPTION
**Pull request by opatut**
Fixes #85 -- I believe.

### CODE REVIEW

**Comment by zombieJ** [comment]
Test case. Pls?

**Comment by opatut** [comment]
> Test case. Pls?

Hi @zombieJ, thanks for reacting to this.

Sadly, the bug ant-design/ant-design#27018 which caused me to trace the problem down into this component is really hard to reproduce, I assume a race condition that only triggers in complex applications due to the browser's timing behaviour (requestAnimationFrame) changing. I do not know how to provide a test case in this standalone environment here, or I would have done it.

**Comment by zombieJ** [comment]
jest can hack timer, and you can inject raf to replace with `setTimeout` instead : )

**Comment by opatut** [comment]
It looks like I was able to build a test case. I think raf is not the issue, since that was actually only relevant in producing the race condition through rc-trigger -- I built a test case just with the existing hacked timers. I made sure to comment what is causing the issue for me and why I'm testing it in the test case itself.

Note that this *is* changing behaviour, and it could be argued that the behaviour from before my changes was the correct one. I think however it is faulty, because it is caused by an internal setTimeout that is mostly invisible to the user. I think the new behaviour is more in line with what I would expect as a user, and it fixes the problem that occurs in ant-design (linked above).

**Comment by giorgi-m** [comment]
@zombieJ The antd [issue ](https://github.com/ant-design/ant-design/issues/27018)referenced by opatut above was closed by bot, please take a look at that one as several developers have encountered that, and it was hard to reproduce.

**Comment by zombieJ** [comment]
`+ rc-align@4.0.9`

**Pull request merged**
